name: Update

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/**
      - .github/actions/**
      - PKGBUILD
      - visual-studio-code-insiders.desktop
      - visual-studio-code-insiders-url-handler.desktop
  workflow_dispatch:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  get-upstream-version:
    name: Get upstream version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
      sha256-x86_64: ${{ steps.sha256-x86_64.outputs.hash }}
    steps:
      - uses: actions/checkout@v2
      - name: Download latest tar
        run: curl -JLO "$(cat PKGBUILD | grep -Po "_src_x86_64=\"\K.+\"" | rev | cut -c2- | rev)"
      - name: Extract version number from tar
        id: get-version
        run: |
          version="$(echo ./code-insider-*.tar.gz | grep -Po "\.\/code-insider-\K.+" | rev | cut -c8- | rev)"
          echo "::set-output name=version::${version}"
          echo "Latest version: ${version}"
      - name: Get SHA256 of x86_64 tar
        id: sha256-x86_64
        run: |
          hash="$(sha256sum ./code-insider-*.tar.gz | awk '{ print $1 }')"
          echo "::set-output name=hash::${hash}"
          echo "SHA256 x86_64: ${hash}"

  edit-pkgbuild:
    needs: get-upstream-version
    name: Edit PKGBUILD and push
    runs-on: ubuntu-latest
    outputs:
      updated: ${{ steps.push.outputs.updated }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Update version
        env:
          VERSION: ${{ needs.get-upstream-version.outputs.version }}
          SHA256_x86_64: ${{ needs.get-upstream-version.outputs.sha256-x86_64 }}
        run: python ./.github/actions/update-version/update-version.py
      - name: Package utils
        id: pkg
        uses: ./.github/actions/pkg
      - name: Push update
        id: push
        env:
          VERSION: ${{ needs.get-upstream-version.outputs.version }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add PKGBUILD .SRCINFO
          git diff --cached --exit-code > /dev/null && echo "::set-output name=updated::false" && exit 0 || :
          git commit -m "Updated to $VERSION"
          git push
          echo "Updated"
          echo "::set-output name=updated::true"
      - name: Upload artefact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.pkg.outputs.pkgfile0 }}
          path: ${{ steps.pkg.outputs.pkgfile0 }}

  build-gh-pages:
    name: Build GH Pages
    needs: edit-pkgbuild
    runs-on: ubuntu-latest
    container: archlinux
    if: needs.edit-pkgbuild.outputs.updated == 'true' || github.event_name != 'schedule'
    steps:
      - name: Install dependencies and update
        run: pacman -Syu --noconfirm --noprogressbar --needed base-devel git
      - uses: actions/checkout@v2
        with:
          path: repo/
      - name: Download artefacts
        uses: actions/download-artifact@v2
        with:
          path: pkg/
      - name: Create repo files
        run: |
          mkdir dist/
          mv pkg/*/*.pkg.* dist
          repo-add -R dist/visual-studio-code-insiders.db.tar.gz dist/visual-studio-code-insiders-*.pkg.*
      - name: Generate index
        run: repo/.github/actions/generate-index/generate-index.sh dist
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          user_name: 'github-actions[bot]'
          user_email: '41898282+github-actions[bot]@users.noreply.github.com'
          commit_message: Deploy commit
          force_orphan: true
